In [28]:
# Handaling duplication of data 
import pandas as pd 
data = {
    'Name': ['Bibek', 'Sana', 'Aashish', 'Bibek', 'Sneha', 
             'Anish', 'Aashish', 'Nisha', 'Bibek', 'Rina'],
    'Salary': [50000, 60000, 55000, 50000, 48000, 
               70000, 55000, 65000, 50000, 62000],
    'Loan': [200000, 250000, 220000, 200000, 180000, 
             300000, 220000, 270000, 200000, 260000]
}
data = pd.DataFrame(data)
data

      Name  Salary    Loan
0    Bibek   50000  200000
1     Sana   60000  250000
2  Aashish   55000  220000
3    Bibek   50000  200000
4    Sneha   48000  180000
5    Anish   70000  300000
6  Aashish   55000  220000
7    Nisha   65000  270000
8    Bibek   50000  200000
9     Rina   62000  260000

In [29]:
data.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8     True
9    False
dtype: bool

In [30]:
data["dupicated_data"]=data.drop_duplicates(inplace=True)
data

      Name  Salary    Loan dupicated_data
0    Bibek   50000  200000           None
1     Sana   60000  250000           None
2  Aashish   55000  220000           None
4    Sneha   48000  180000           None
5    Anish   70000  300000           None
7    Nisha   65000  270000           None
9     Rina   62000  260000           None

In [32]:
# remove duplication of data in in large data
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
dataset=pd.read_csv(r"D:\MML\loan_data.csv")
dataset.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
1,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
2,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
3,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
4,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y

In [37]:
dataset.shape

(381, 13)

In [40]:
dataset.drop_duplicates(inplace=True)
dataset.shape

(381, 13)

In [ ]:
#